id: http://marine.gov.scot/metadata/saved/schema/meta/
name: meta
title: >-
  SAVED meta-model
prefixes:
  linkml: https://w3id.org/linkml/
  rap:    http://marine.gov.scot/metadata/saved/rap/
  saved:  http://marine.gov.scot/metadata/saved/schema/
  job:    http://marine.gov.scot/metadata/saved/schema/job_
  
imports:
  - linkml:types
  - ./core
  - ./collected
  - ./descriptive
  - ./job
  - ./modelled
default_prefix: saved

emit_prefixes:
  - rap
  - saved
  - job
